sudo: required

language: node_js

node_js:
  - 20.2.0

services:
  - docker

before_install:
  - docker build -t spadyala-melb/sample-app .
# script:
#   - docker run spadyala-melb/sample-app npm start
